services:
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686" # web
      - "14268:14268" # http
      - "14250:14250" # grpc
    networks:
      - ryan_gitops-network
    

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    ports:
      - "4317:4317" # grpc
      - "55681:55681" # http
    volumes:
      - ./opentelemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: ["--config", "/etc/otel-collector-config.yaml"]
    networks:
      - ryan_gitops-network

networks:
  ryan_gitops-network:
    external: true